### PR TITLE
Endorama add image alt tag parser

### PR DESCRIPTION
**Pull request by vecna**
@endorama this is the new PR

### CODE REVIEW

**Comment by endorama** [comment]
Hello @vecna, sorry for not being active on this, do you need any help?

**Comment by vecna** [comment]
Hi @endorama, 
I was supposing to complete the integration alone, but I got overwhelmed by other tasks, so I was keeping the PR open. 

I left some comments in #60. I looked now to provide a summary, and there is only one problem still to be addressed:

- [ ] do not extract the `alt text` from the profile pictures

**Comment by endorama** [comment]
I've checked the facebook post's HTML, the main differences between profile picture and content picture are highlighted below. Which path do you think is more suitable?

---
Profile picture:
```html
<a class="_5pb8 _8o _8s lfloat _ohe" 
   href="https://www.facebook.com/..." 
   aria-hidden="true" tabindex="-1" 
   target="" 
   data-ft="{&quot;tn&quot;:&quot;m&quot;}" 
   data-hovercard="/ajax/hovercard/user.php?..."
   data-hovercard-prefer-more-content-show="1" 
   aria-controls="js_uk" 
   aria-haspopup="true" 
   aria-describedby="js_ul" 
   id="js_um">
  <div class="_38vo">
    <img class="_s0 _5xib _5sq7 _44ma _rw img" 
         src="https://scontent-mxp1-1.xx.fbcdn.net/v/..." 
         alt="" 
         aria-label="..." role="img">
  </div>
</a>
```
---
Content picture:
```html
<a class="_5dec _xcx" href="https://www.facebook.com/photo.php?..." 
   rel="theater" 
   ajaxify="https://www.facebook.com/photo.php?..." 
   data-ploi="https://scontent-mxp1-1.xx.fbcdn.net/v/..." 
   data-render-location="newsstand" 
   data-ft="{&quot;tn&quot;:&quot;E&quot;}" 
   id="u_jsonp_3_2o" 
   style="top:0px; left:0px; width: 237px; height: 237px;">
  <div class="_46-h" style="width:237px;height:237px;">
    <img class="_46-i img"
         src="https://scontent-mxp1-1.xx.fbcdn.net/v/..." 
         style="left:-56px; top:0px;" alt="No automatic alt text available." 
         width="386" height="240">
  </div>
</a>
```
---
Best hook point seems to be the `_46-i` class set on the content image (opposed to the bunch of other classes).   
Also hovercard attributes are not present on parent link for content images.

PS: BTW I don't think I have write permission on the repo, so after fixing this should I attach a git patch here?

**Comment by vecna** [comment]
It is better don't use the classes like `_46-i`, they are browser and language dependent. I guess the best is exclude the elements with ` data-hovercard="/ajax/hovercard/user.php?` in the father `div`. data-hovercard is applied to all the profiles pictures. is the only different I can figure out 

fork this branch to do your patch. when we meet you will be a welcomed contributor :)

**Comment by vecna** [comment]
I was really hoping to get your contribute to close this ;)

**Pull request merged**
