### PR TITLE
docker beta release

### PR DESCRIPTION
**Pull request by gibix**

### CODE REVIEW

**Comment by vecna** [comment]
Thanks :)
but did you use it? in which use cases is going to be used? I didn't hear yet anybody raising the need for a

**Comment by gibix** [comment]
Is the best way to have the first test locally and if you don't want to touch your local os with npm/node/mongo.
Could be interesting to push also our mongo container with a fixed base of data to play with.

**Comment by vecna** [comment]
@gibix this is a pretty nice idea! Because can be helpful for parsers developer (#44) 
providing only a selected amount of HTMLs from users who explicitly opt-in.

That can solve some other locking issue, nice. Think how to do it, and I'll cover the rest,
happy new year :)

**Comment by gibix** [comment]
We can:
1 - an importer script that pull from our master server only the snipped data that we selected
2 - use that script to regularly update a "stable" mongo container

**Comment by vecna** [comment]
Yes, and they are on init and executed once a week respectively. 

in both of the task, has to be:
1. download a .tar.gz
2. decompress
3. run mongorestore over it

this update automatically present records

**Comment by gibix** [comment]
Perfetct, the dump should be done of the raw data in htmls2

**Comment by vecna** [comment]
not only (also to provide coherence in timelines and impressions)
and not all of them (only few users among us opting in)

**Pull request merged**
